=== giellatekno/oahpa/view/sme/src/main/webapp/activities/activity.dtd
<!ELEMENT activity ( meta, client-cfg, server-cfg ) >
<!ATTLIST activity enabled NMTOKEN #REQUIRED >
<!ATTLIST activity version NMTOKEN #REQUIRED >
<!ELEMENT author ( #PCDATA ) >
<!ELEMENT client-cfg ( entry+ ) >
<!ELEMENT entry EMPTY >
<!ATTLIST entry key NMTOKEN #REQUIRED >
<!ATTLIST entry overridable (yes|no) "yes" >
<!ATTLIST entry value CDATA #REQUIRED >
<!ELEMENT meta ( name, author+ ) >
<!ELEMENT name ( #PCDATA ) >
<!ELEMENT pipeline EMPTY >
<!ATTLIST pipeline desc CDATA #REQUIRED >
<!ELEMENT post ( pipeline, entry* ) >
<!ELEMENT pre ( pipeline, entry* ) >
<!ELEMENT server-cfg ( pre, post ) >

=== giellatekno/oahpa/view/sme/src/main/webapp/activities_old/Gerunds/activity.xml
<?xml version="1.0" ?>
<!-- Single configuration file for an activity. -->
<!-- <!DOCTYPE activity SYSTEM "../activity.dtd"> -->
<activity version="0.1" enabled="yes">
	<meta>
		<name>Gerunds vs. Infinitives</name>
		<author>Niels Ott</author>
		<author>Ramon Ziai</author>
	</meta>	
	
	<!-- the client configuration will be converted to JavaScript ending up in  the browser  -->
	<client-cfg>
		<!-- enhancement styles for the colorize activity -->
		<entry key="enhancementStyleGER" value="color: #ce6006; font-weight:bold" overridable="yes"/>
		<entry key="enhancementStyleINF" value="color: #8c01c0; font-weight:bold" overridable="yes"/>
		<entry key="enhancementStyleCLU_GERONLY" value="color: #2222ff; font-weight:bold" overridable="yes"/>
		<entry key="enhancementStyleCLU_INFONLY" value="color: #2222ff; font-weight:bold" overridable="yes"/>
		<entry key="enhancementStyleCLU_BOTHMEANSAME" value="color: #2222ff; font-weight:bold" overridable="yes"/>
		<entry key="enhancementStyleCLU_BOTHMEANDIFF" value="color: #2222ff; font-weight:bold" overridable="yes"/>
		<entry key="enhancementStyleCLU_FIXEDEXP" value="color: #2222ff; font-weight:bold" overridable="yes"/>
		<!-- this is the default style for the input box in a cloze activity: -->
		<entry key="clozeDefaultStyle" value="font-weight:bold; width:75px; border:1px solid black; background:white;" overridable="yes"/>
		<!-- the input box in a cloze activity is set to this style if the input was wrong: -->
		<entry key="clozeWrongStyle" value="color: red; font-weight:bold; width:75px; border:1px solid black; background:white;" overridable="yes"/>
		<!-- the input box is replaced by a text of this style if the input was correct: -->
		<entry key="clozeCorrectStyle" value="color: green; font-weight:bold" overridable="yes"/>
		<!-- show hint questionmarks in cloze activity? if so, define their style... -->
		<entry key="clozeShowHints" value="yes" overridable="yes" />
		<entry key="clozeHintStyle" value="font-weight:regular; width:15px; border:1px solid #A0A0A0; background:#E9E9E9; color:#A0A0A0; margin-left:2px;" overridable="yes"/>
		<entry key="clozeHintSolvedStyle" value="color: #22F; font-weight:bold" overridable="yes"/>
	</client-cfg>
	<!--  this is the UIMA AE configuration for the pipeline -->
	<server-cfg>
		<lang code="en">
			<pre>
				<!-- the pipeline descriptor is looked up in the class path, must begin with / -->
				<pipeline desc="/operators/vislcg3Pipe.xml"/>
				<entry key="vislcg3Loc" value="/usr/local/werti/bin/vislcg3" overridable="no"/>
				<!-- relative paths should be interpreted as relative to the respective activity directory -->
				<entry key="vislcg3GrammarLoc" value="_ACT_/resources/gerundsgrammar" overridable="no"/>
			</pre>
			<post>
				<!-- the pipeline descriptor is looked up in the class path, must begin with / -->
				<pipeline desc="/operators/vislCGPostProc.xml"/>
				<entry key="chunkTags" value="INF,GER,CLU-GERONLY,CLU-INFONLY,CLU-BOTHMEANSAME,CLU-BOTHMEANDIFF,CLU-FIXEDEXP,PRO,PAR,GOI,GOP,AMB,RELEVANT" overridable="no"/>
			</post>
		</lang>
	</server-cfg>
</activity>

=== giellatekno/oahpa/view/sme/src/main/webapp/activities_old/Arts/activity.xml
<?xml version="1.0" ?>
<!-- Single configuration file for an activity. -->
<!-- <!DOCTYPE activity SYSTEM "../activity.dtd"> -->
<activity version="0.1" enabled="yes">
	<meta>
		<name>Articles</name>
		<author>Adriane Boyd</author>
	</meta>

	<client-cfg>
	   		<!-- the enhancement style for a colorize activity: -->
		<entry key="colorizeStyle" value="color: #22F; font-weight:bold" overridable="yes"/>
		<!-- this is the default style for the input box in a cloze activity: -->
		<entry key="clozeDefaultStyle" value="font-weight:bold; width:35px; border:1px solid black; background:white;" overridable="yes"/>
		<!-- the input box in a cloze activity is set to this style if the input was wrong: -->
		<entry key="clozeWrongStyle" value="color: red; font-weight:bold; width:35px; border:1px solid black; background:white;" overridable="yes"/>
		<!-- the input box is replaced by a text of this style if the input was correct: -->
		<entry key="clozeCorrectStyle" value="color: green; font-weight:bold" overridable="yes"/>
		<!-- show hint questionmarks in cloze activity? if so, define their style... -->
		<entry key="clozeShowHints" value="yes" overridable="yes" />
		<entry key="clozeHintStyle" value="font-weight:regular; width:15px; border:1px solid #A0A0A0; background:#E9E9E9; color:#A0A0A0; margin-left:2px;" overridable="yes"/>
		<entry key="clozeHintSolvedStyle" value="color: #22F; font-weight:bold" overridable="yes"/>

	</client-cfg>
	<!--  this is the UIMA AE configuration for the pipeline -->
	<server-cfg>
		<lang code="en">
			<pre>
				<!-- the pipeline descriptor is looked up in the class path, must begin with / -->
				<pipeline desc="/operators/OpenNlpTokenizerPipe.xml"/>
			</pre>
			<post>
				<!-- the pipeline descriptor is looked up in the class path, must begin with / -->
				<pipeline desc="/enhancers/WordEnhancer.xml"/>
				<entry key="Words" value="a,an,the" overridable="yes"/>
			</post>
		</lang>
	</server-cfg>
</activity>

=== giellatekno/oahpa/view/sme/src/main/webapp/activities/Conjunctions/activity.xml
<?xml version="1.0" ?>
<!-- Single configuration file for an activity. -->
<!-- <!DOCTYPE activity SYSTEM "../activity.dtd"> -->
<activity version="0.1" enabled="yes">
	<meta>
		<name>Conjunctions</name>
		<author>Adriane Boyd, Heli Uibo</author>
	</meta>
	
	<!-- the client configuration will be converted to JavaScript ending up in  the browser  -->
	<client-cfg>
	<!-- the client-cfg is in js-lib for newer releases, f ex WERTiCore -->
	   		<!-- the enhancement style for a colorize activity: -->
		<entry key="colorizeStyle" value="color: #22F; font-weight:bold" overridable="yes"/>
		<!-- this is the default style for the input box in a cloze activity: -->
		<entry key="clozeDefaultStyle" value="font-weight:bold; width:35px; border:1px solid black; background:white;" overridable="yes"/>
		<!-- the input box in a cloze activity is set to this style if the input was wrong: -->
		<entry key="clozeWrongStyle" value="color: red; font-weight:bold; width:35px; border:1px solid black; background:white;" overridable="yes"/>
		<!-- the input box is replaced by a text of this style if the input was correct: -->
		<entry key="clozeCorrectStyle" value="color: green; font-weight:bold" overridable="yes"/>
		<!-- show hint questionmarks in cloze activity? if so, define their style... -->
		<entry key="clozeShowHints" value="yes" overridable="yes" />
		<entry key="clozeHintStyle" value="font-weight:regular; width:15px; border:1px solid #A0A0A0; background:#E9E9E9; color:#A0A0A0; margin-left:2px;" overridable="yes"/>
		<entry key="clozeHintSolvedStyle" value="color: #22F; font-weight:bold" overridable="yes"/>

	</client-cfg>
	<!--  this is the UIMA AE configuration for the pipeline -->
	<server-cfg>
		<lang code="en"> <!-- because there is no tokenizer for lang=sme -->
			<pre>
				<!-- the pipeline descriptor is looked up in the class path, must begin with / -->
				<pipeline desc="/operators/vislcg3Pipe.xml"/>
			</pre>
			<post>
				<!-- the pipeline descriptor is looked up in the class path, must begin with / -->
				<pipeline desc="/operators/vislcg3PostProc.xml"/>
				<entry key="conjunctionTags" value="CC,CS" overridable="yes"/>  
			</post>
		</lang>
	</server-cfg>
</activity>
