=== giellatekno/oahpa/dtd/questions.dtd
<!-- question.dtd							  -->
<!-- DTD for question templates used in OAHPA -->

<!-- The dtd as it is now is strictly descriptive, the attlists are	  -->
<!-- collected as follows:											  -->
<!-- cat questions_* | grep ' class' | cut -d"\"" -f2 | sort -u | see -->


<!ELEMENT questions (q+)>

<!ELEMENT q (qtype, question, answer)>

<!ELEMENT qtype (#PCDATA)>

<!ELEMENT question (text, element+)>

<!ELEMENT text (#PCDATA)>

<!ELEMENT element (grammar?, id?, sem? )>
<!ATTLIST element
    type ( CONNEG
         | INTERR
         | MAINV
         | MAINV2
         | N-ACC
         | N-COM
         | N-ESS
         | N-GEN
         | N-ILL
         | N-LOC
         | NEG
         | NOUN
         | NUM-ATTR
         | OBJ
         | PLACE
         | PRED
         | PREDCOMP
         | PREDSUP
         | PRFPRC
         | SUBJ
         | V-POT
         ) #IMPLIED
>

<!ELEMENT grammar EMPTY >
<!ATTLIST grammar
	pos ( A
        | N
        | Pron
        ) #IMPLIED
>    

<!ATTLIST grammar
	tag ( HUMAN
        | N
        | A+Attr
        | V+Act+Ind+Prs+Sg3
        | A+Comp+Number+Nom
        | A+Number+Nom
        | A+Superl+Number+Nom
        | N+Acc+Number
        | N+Ess
        | N+Num+Sg+Acc
        | N+Num+Sg+Com
        | N+Num+Sg+Gen
        | N+Num+Sg+Ill
        | N+Num+Sg+Loc
        | N+Num+Sg+Nom
        | N+Number+Loc
        | N+Number+Nom
        | N+Pl+Acc
        | N+Pl+Ill
        | N+Pl+Loc
        | N+Pl+Nom
        | N+Sg+Acc
        | N+Sg+Com
        | N+Sg+Gen
        | N+Sg+Ill
        | N+Sg+Loc
        | N+Sg+Nom
        | Neg+Ind+Person-Number
        | Num+Ess
        | Num+Pl+Acc
        | Num+Pl+Gen
        | Num+Sg+Acc
        | Num+Sg+Com
        | Num+Sg+Gen
        | Pron+Interr+Number+Acc
        | Pron+Interr+Number+Com
        | Pron+Interr+Number+Gen
        | Pron+Interr+Number+Ill
        | Pron+Interr+Number+Loc
        | Pron+Pers+Du1
        | Pron+Pers+Du3+Nom
        | Pron+Pers+Person-Number
        | Pron+Pers+Person-Number+Nom
        | Pron+Pers+Pl1+Nom
        | Pron+Pers+Sg1
        | Pron+Pers+mun+Sg1
        | Pron+Pers+mun+Sg1+Nom
        | Pron+Person-Number+Nom
        | Pron+son+Person-Number+Nom
        | V+Cond+Prs+ConNeg
        | V+Cond+Prs+Du1
        | V+Cond+Prs+Du3
        | V+Cond+Prs+Person-Number
        | V+Cond+Prs+Pl1
        | V+Cond+Prs+Sg1
        | V+Imprt+Prs+Du1
        | V+Imprt+Prs+Du2
        | V+Imprt+Prs+Pl1
        | V+Imprt+Prs+Pl2
        | V+Imprt+Prs+Sg2
        | V+Ind+Person-Number
        | V+Ind+Prs+Du3
        | V+Ind+Prs+Person-Number
        | V+Ind+Prs+Sg2
        | V+Ind+Prt+Du3
        | V+Ind+Prt+Person-Number
        | V+Ind+Tense+Person-Number
        | V+Ind+Tense+Pl3
        | V+Ind+Tense+Sg2
        | V+Inf
        | V+Pot+Person-Number
        | V+PrfPrc
	    ) #IMPLIED
>
	      
<!ELEMENT id (#PCDATA)>

<!ELEMENT sem EMPTY >
<!ATTLIST sem 
    class ( ACTIVITY
          | ANIMAL
          | ARRANGEMENT-PL
          | BUILDING
          | CLOTHES-adj
          | CLOTHING
          | CLOTHING-PL
          | COLL-NUM
          | COMV
          | FAMILY
          | HUMAN
          | HUMAN-adj
          | MYTH
          | MYTH-HUMAN
          | OBJECT
          | PLACE
          | PLACE-NAME
          | PROFESSION
          | SLIDE-TOOL
          | TIME-POINT-GEN
          | VEHICLE
          ) #IMPLIED 
>

<!ELEMENT answer (text, element+)>

=== giellatekno/oahpa/sme_oahpa_project/sme_data/meta/derivation_questions.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
<!DOCTYPE lexicon  PUBLIC '-//XMLmind//DTD lexicon//FI'  '../../dtd/questions.dtd'>
-->

<questions>
  <q id="derav1">
    <qtype>A-DER-V</qtype>
   <question>
      <text>Mo manná PERS</text>
      <element id="PERS">
	<grammar tag="N+Prop+Sg+Com"/>
	<sem class="mPERSNAME"/>
      </element>
    </question>
    <answer> 
      <text>Son lea maŋimuš áigge VERB</text>
      <element game='morfa' id="VERB" task="yes" >
	<sem class="mOLBMO_V"/>
	<grammar tag="A+Der/AV+V+PrfPrc"/>
      </element>
    </answer>
  </q> 
  <q id="derav2">
    <qtype>A-DER-V</qtype>
   <question>
      <text>Mo manai PERS doppe</text>
      <element id="PERS">
	<grammar tag="N+Prop+Sg+Com"/>
	<sem class="mPERSNAME"/>
      </element>
    </question>
    <answer> 
      <text>Son duođaid VERB</text>
      <element game='morfa' id="VERB" task="yes" >
	<sem class="mOLBMO_V"/>
	<grammar tag="A+Der/AV+V+Ind+Prt+Sg3"/>
      </element>
    </answer>
  </q> 
  <q id="derav3">
    <qtype>A-DER-V</qtype>
   <question>
      <text>Mo dus manai PLACE</text>
      <element id="PLACE">
	<grammar tag="N+Prop+Sg+Loc"/>
	<sem class="mPLACENAME"/>
      </element>
    </question>
    <answer> 
      <text>Mun duođaid VERB doppe</text>
      <element game='morfa' id="VERB" task="yes" >
	<sem class="mOLBMO_V"/>
	<grammar tag="A+Der/AV+V+Ind+Prt+Sg1"/>
      </element>
    </answer>
  </q> 
  <q id="derav4">
    <qtype>A-DER-V</qtype>
   <question>
      <text>Mo lei dalle go bohtet ruoktot</text>
    </question>
    <answer> 
      <text>Dalle lei VERB</text>
      <element game='morfa' id="VERB" task="yes" >
	<sem class="mWEATHER_V"/>
	<grammar tag="A+Der/AV+V+PrfPrc"/>
      </element>
    </answer>
    <answer> 
      <text>VERB ovdalgo mun bohten</text>
      <element game='morfa' id="VERB" task="yes" >
	<sem class="mWEATHER_V"/>
	<grammar tag="A+Der/AV+V+Ind+Prt+Sg3"/>
      </element>
    </answer>
  </q> 
  <q id="derav5">
    <qtype>A-DER-V</qtype>
   <question>
      <text>Suitet go oastit dien biilla</text>
    </question>
    <answer> 
      <text>In dieđe vuos, oainnán ahte lea VERB</text>
      <element game='morfa' id="VERB" task="yes" >
	<sem class="mBIILA_V"/>
	<grammar tag="A+Der/AV+V+PrfPrc"/>
      </element>
    </answer>
  </q> 
  <q id="derav6">
    <qtype>A-DER-V</qtype>
   <question>
      <text>Ledje go buorit heajat</text>
    </question>
    <answer> 
      <text>Ledje, muhto mun nu VERB</text>
      <element game='morfa' id="VERB" task="yes" >
	<sem class="mFEASTA_V"/>
	<grammar tag="A+Der/AV+V+Ind+Prt+Sg1"/>
      </element>
    </answer>
  </q> 
  <q id="derav7">
    <qtype>A-DER-V</qtype>
   <question>
      <text>Manne don háliidat molsut buvssaid</text>
    </question>
    <answer> 
      <text>Mu buvssat leat VERB</text>
      <element game='morfa' id="VERB" task="yes" >
	<sem class="mBAIDI_V"/>
	<grammar tag="A+Der/AV+V+PrfPrc"/>
      </element>
    </answer>
    <answer> 
      <text>Mu buvssat VERB</text>
      <element game='morfa' id="VERB" task="yes" >
	<sem class="mBAIDI_V"/>
	<grammar tag="A+Der/AV+V+Ind+Prt+Pl3"/>
      </element>
    </answer>
  </q> 
  <q id="derav8">
    <qtype>A-DER-V</qtype>
   <question>
      <text>Mii dáhpáhuvai du čáppa gáktái</text>
    </question>
    <answer> 
      <text>Mu gákti VERB</text>
      <element game='morfa' id="VERB" task="yes" >
	<sem class="mBAIDI_V"/>
	<grammar tag="A+Der/AV+V+Ind+Prt+Sg3"/>
      </element>
    </answer>
  </q> 
  <q id="derav9">
    <qtype>A-DER-V</qtype>
   <question>
      <text>Mo manai mánáin riegádanfeasttas</text>
    </question>
    <answer> 
      <text>Bures, muhto sii nu VERB</text>
      <element game='morfa' id="VERB" task="yes" >
	<sem class="mFEASTA_V"/>
	<grammar tag="A+Der/AV+V+Ind+Prt+Pl3"/>
      </element>
    </answer>
  </q> 
  <q id="derav10">
    <qtype>A-DER-V</qtype>
   <question>
      <text>Mii lea dáhpáhuvvan du čáppa gáktái</text>
    </question>
    <answer> 
      <text>Mu gákti lea VERB</text>
      <element game='morfa' id="VERB" task="yes" >
	<sem class="mBAIDI_V"/>
	<grammar tag="A+Der/AV+V+PrfPrc"/>
      </element>
    </answer>
  </q> 
  <q id="dervv1">
    <qtype>DER-PASSV</qtype>
   <question>
      <text>Áiggut go oastit dien ITEM</text>
      <element id="ITEM">
	<sem class="CLOTHING"/>
	<grammar tag="N+Nountype+Sg+Acc"/>
      </element>
    </question>
    <answer> 
      <text>In áiggo, dat VERB juo ikte</text>
      <element game='morfa' id="VERB" task="yes" >
	<id>vuovdit</id>
	<grammar tag="V+Der/PassL+V+Ind+Prt+Sg3"/>
      </element>
    </answer>
  </q> 
  <q id="dervv2">
    <qtype>DER-PASSV</qtype>
   <question>
      <text>Áiggut go oastit dien ITEM</text>
      <element id="ITEM">
	<sem class="mPRIVVEHICLE"/>
	<grammar tag="N+Nountype+Sg+Acc"/>
      </element>
    </question>
    <answer> 
      <text>In áiggo, dat VERB juo ikte</text>
      <element game='morfa' id="VERB" task="yes" >
	<id>vuovdit</id>
	<grammar tag="V+Der/PassL+V+Ind+Prt+Sg3"/>
      </element>
    </answer>
  </q> 
  <q id="dervv3">
    <qtype>DER-PASSV</qtype>
   <question>
      <text>Goas áiggut divvut ITEM</text>
      <element id="ITEM">
	<sem class="mPRIVVEHICLE"/>
	<grammar tag="N+Nountype+Sg+Acc"/>
      </element>
    </question>
    <answer> 
      <text>Dat VERB juo ikte</text>
      <element game='morfa' id="VERB" task="yes" >
	<id>divvut</id>
	<grammar tag="V+Der/PassL+V+Ind+Prt+Sg3"/>
      </element>
    </answer>
  </q> 
  <q id="dervv4">
    <qtype>DER-PASSV</qtype>
   <question>
      <text>Lea go dus ruhta máksit ITEM</text>
      <element id="ITEM">
	<sem class="mPRIVVEHICLE"/>
	<grammar tag="N+Nountype+Sg+Acc"/>
      </element>
    </question>
    <answer> 
      <text>ITEM lea juo VERB</text>
      <element id="ITEM" content="ITEM">
	<grammar tag="N+Nountype+Sg+Nom"/>
      </element>
      <element game='morfa' id="VERB" task="yes" >
	<id>máksit</id>
	<grammar tag="V+Der/PassL+V+PrfPrc"/>
      </element>
    </answer>
  </q> 
  <q id="dervv5">
    <qtype>DER-PASSV</qtype>
   <question>
      <text>Mii dáhpáhuvai biergguin</text>
    </question>
    <answer> 
      <text>Biergu lea VERB</text>
      <element game='morfa' id="VERB" task="yes" >
	<id>borrat</id>
	<grammar tag="V+Der/PassL+V+PrfPrc"/>
      </element>
    </answer>
    <answer> 
      <text>Biergu lea juo VERB</text>
      <element game='morfa' id="VERB" task="yes" >
	<sem class="mCOOK"/>
	<grammar tag="V+Der/PassL+V+PrfPrc"/>
      </element>
    </answer>
    <answer> 
      <text>Buot biergu VERB</text>
      <element game='morfa' id="VERB" task="yes" >
	<sem class="mCOOK"/>
	<grammar tag="V+Der/PassL+V+Ind+Prt+Sg3"/>
      </element>
    </answer>
    <answer> 
      <text>Biergu lea VERB niestin</text>
      <element game='morfa' id="VERB" task="yes" >
	<id>geavahit</id>
	<grammar tag="V+Der/PassL+V+PrfPrc"/>
      </element>
    </answer>
    <answer> 
      <text>Biergu lea VERB niestin</text>
      <element game='morfa' id="VERB" task="yes" >
	<id>atnit</id>
	<grammar tag="V+Der/PassL+V+PrfPrc"/>
      </element>
    </answer>
  </q> 
  <q id="dervv6">
    <qtype>DER-PASSV</qtype>
   <question>
      <text>Man boarrásat duot viesut leat</text>
    </question>
    <answer> 
      <text>Dat VERB 50-logus</text>
      <element game='morfa' id="VERB" task="yes" >
	<id>hukset</id>
	<grammar tag="V+Der/PassL+V+Ind+Prt+Pl3"/>
      </element>
    </answer>
  </q> 
  <q id="dervv7">
    <qtype>DER-PASSV</qtype>
   <question>
      <text>Man boarrásat ITEM leat</text>
      <element id="ITEM">
	<sem class="mPRINTEDMATTER"/>
	<grammar tag="N+Nountype+Pl+Nom"/>
      </element>
    </question>
    <answer> 
      <text>Dat VERB soađi áigge</text>
      <element game='morfa' id="VERB" task="yes" >
	<id>čállit</id>
	<grammar tag="V+Der/PassL+V+Ind+Prt+Pl3"/>
      </element>
    </answer>
    <answer> 
      <text>Dat VERB moadde jagi dás ovdal</text>
      <element game='morfa' id="VERB" task="yes" >
	<id>almmuhit</id>
	<grammar tag="V+Der/PassL+V+Ind+Prt+Pl3"/>
      </element>
    </answer>
  </q> 
  <q id="dervv8">
    <qtype>DER-PASSV</qtype>
   <question>
      <text>Manne oasttát nu ollu ITEM</text>
      <element id="ITEM">
	<sem class="mPRINTEDMATTER"/>
	<grammar tag="N+Nountype+Pl+Acc"/>
      </element>
    </question>
    <answer> 
      <text>Dat VERB oahpahussii</text>
      <element game='morfa' id="VERB" task="yes" >
	<id>dárbbašit</id>
	<grammar tag="V+Der/PassL+V+Ind+Prs+Pl3"/>
      </element>
    </answer>
    <answer> 
      <text>Dat VERB oahpahusas</text>
      <element game='morfa' id="VERB" task="yes" >
	<id>geavahit</id>
	<grammar tag="V+Der/PassL+V+Ind+Prs+Pl3"/>
      </element>
    </answer>
    <answer> 
      <text>Dat VERB oahpahusas</text>
      <element game='morfa' id="VERB" task="yes" >
	<id>atnit</id>
	<grammar tag="V+Der/PassL+V+Ind+Prs+Pl3"/>
      </element>
    </answer>
  </q> 
  <q id="dervv9">
    <qtype>DER-PASSV</qtype>
   <question>
      <text>Dat han lea fiinna ITEM</text>
      <element id="ITEM">
	<sem class="BUILDING"/>
	<grammar tag="N+Nountype+Sg+Nom"/>
      </element>
    </question>
    <answer> 
      <text>Dat VERB diibmá</text>
      <element game='morfa' id="VERB" task="yes" >
	<sem class="mBUILD"/>
	<grammar tag="V+Der/PassL+V+Ind+Prt+Pl3"/>
      </element>
    </answer>
    <answer> 
      <text>Dat leage aiddo VERB</text>
      <element game='morfa' id="VERB" task="yes" >
	<sem class="mBUILD"/>
	<grammar tag="V+Der/PassL+V+PrfPrc"/>
      </element>
    </answer>
  </q> 
  <q id="dervv10">
    <qtype>DER-PASSV</qtype>
   <question>
      <text>Goas eadni oažžu ođđa stuolut</text>
    </question>
    <answer> 
      <text>Dat VERB gaskavahku</text>
      <element game='morfa' id="VERB" task="yes" >
	<id>viežžat</id>
	<grammar tag="V+Der/PassL+V+Ind+Prs+Pl3"/>
      </element>
    </answer>
    <answer> 
      <text>Dat VERB ihttin</text>
      <element game='morfa' id="VERB" task="yes" >
	<id>buktit</id>
